SELECT STORAGE.SKU_CODE AS STORAGE_SKU_CODE,
       SHARE_STORAGE.SKU_CODE AS SHARE_STORAGE_SKU_CODE,
       CHANNEL_STORAGE.SKU_CODE AS CHANNEL_STORAGE_SKU_CODE,
       WAREHOUSE.NAME AS XXX_NAME,
      --(SELECT NAME FROM NEO_WAREHOUSE  X WHERE X.ID =STORAGE.WAREHOUSE_ID)  AS WAREHOUSE_NAME,
       SHARE_STORE.NAME AS XXX_SHARE_STORE_NAME,
       --(SELECT NAME FROM NEO_SHARE_STORE  X WHERE X.ID =SHARE_STORAGE.SHARE_STORE_ID)  AS SHARE_STORE_NAME,
       CHANNEL.NAME AS XXX_CHANNEL_NAME,
     --  (SELECT NAME FROM NEO_CHANNEL  X WHERE X.ID =CHANNEL_STORAGE.CHANNEL_ID)  AS CHANNEL_NAME,
       (SELECT NAME FROM NEO_WAREHOUSE  X WHERE X.ID =WAHREHOUSE_RATIO.WAREHOUSE_ID) || '=>' ||
       (SELECT NAME FROM NEO_SHARE_STORE  X WHERE X.ID =WAHREHOUSE_RATIO.SHARE_STORE_ID) || 
       (SELECT NAME FROM NEO_CHANNEL  X WHERE X.ID = CHANNEL_RATIO.CHANNEL_ID)AS WAREHOUSE_TO_SHARE_TO_CHANNEL,
       STORAGE.QTY_PREOUT AS STORAGE_QTY_PREOUT,
       STORAGE.QTY_PREIN AS STORAGE_QTY_PREIN,
       STORAGE.QTY_STORAGE AS STORAGE_QTY_STORAGE,
       STORAGE.QTY_SHARE AS STORAGE_QTY_SHARE,
       STORAGE.QTY_AVAILABLE AS STORAGE_QTY_AVAILABLE,
       
       SHARE_STORAGE.SKU_CODE AS SHARE_STORAGE_SKU_CODE,
       SHARE_STORAGE.SHARE_STORE_ID AS SHARE_STORAGE_SHARE_STORE_ID,
       SHARE_STORAGE.QTY_PREOUT AS SHARE_STORAGE_QTY_PREOUT,
       SHARE_STORAGE.QTY_PREIN AS SHARE_STORAGE_QTY_PREIN,
       SHARE_STORAGE.QTY_STORAGE AS SHARE_STORAGE_QTY_STORAGE,
       
       CHANNEL_STORAGE.SKU_CODE AS CHANNEL_STORAGE_SKU_CODE,
       CHANNEL_STORAGE.CHANNEL_ID AS CHANNEL_STORAGE_CHANNEL_ID ,
       CHANNEL_STORAGE.QTY_PREOUT AS CHANNEL_STORAGE_QTY_PREOUT,
       CHANNEL_STORAGE.QTY_PREIN AS CHANNEL_STORAGE_QTY_PREIN,
       CHANNEL_STORAGE.QTY_STORAGE AS CHANNEL_STORAGE_QTY_STORAGE,
       
       CHANNEL_RATIO.CHANNEL_ID,
       CHANNEL_RATIO.SHARE_STORE_ID,
       CHANNEL_RATIO.RATIO,
       
       WAHREHOUSE_RATIO.WAREHOUSE_ID,
       WAHREHOUSE_RATIO.SHARE_STORE_ID,
       WAHREHOUSE_RATIO.RATIO

  FROM NEO_SHARE_CHANNEL_RATIO CHANNEL_RATIO,
       NEO_WAREHOUSE_SHARE_RATIO WAHREHOUSE_RATIO,
       NEO_CHANNEL_STORAGE CHANNEL_STORAGE,
       NEO_SHARE_STORAGE SHARE_STORAGE,
       NEO_CHANNEL  CHANNEL,
       NEO_SHARE_STORE SHARE_STORE,
       NEO_WAREHOUSE WAREHOUSE,
       NEO_STORAGE STORAGE
 WHERE CHANNEL_RATIO.SHARE_STORE_ID = SHARE_STORE.ID
   AND CHANNEL_RATIO.CHANNEL_ID = CHANNEL.ID
   AND WAHREHOUSE_RATIO.WAREHOUSE_ID = WAREHOUSE.ID
   AND WAHREHOUSE_RATIO.SHARE_STORE_ID = SHARE_STORE.ID
   AND STORAGE.WAREHOUSE_ID = WAREHOUSE.ID
   AND CHANNEL.ID = CHANNEL_STORAGE.CHANNEL_ID
   AND STORAGE.SKU_CODE = SHARE_STORAGE.SKU_CODE
   AND SHARE_STORE.ID = SHARE_STORAGE.SHARE_STORE_ID
   AND STORAGE.SKU_CODE = CHANNEL_STORAGE.SKU_CODE
   AND STORAGE.SKU_CODE = 63633 
   AND CHANNEL_RATIO.CHANNEL_ID = 1752 
